#!/bin/bash

for i; do
	if  echo "$i" | grep -P '(?=^.{4,253}$)(^(?:[a-zA-Z](?:(?:[a-zA-Z0-9\-]){,61}[a-zA-Z])?\.)+[a-zA-Z]{2,}$)' >> /dev/null
	then
		if grep -q -x "$dnslock_iface_ip	$i" "/etc/DNSlock/blacklist.list"; 
		then
        	echo "$i is already in the IPv4 blacklist, checking in IPv6 blacklist."
 		else
			echo "Adding $i to IPv4 blacklist"
			echo "$dnslock_iface_ip	$i" >> /etc/DNSlock/blacklist.list
		fi
		
		if grep -q -x "$dnslock_iface_ipv6	$i" "/etc/DNSlock/blacklist.list"; 
		then
        	echo "$i is already in the IPv6 blacklist, no further action is required."
 		else
			echo "Adding $i to IPv6 blacklist"
			echo "$dnslock_iface_ipv6	$i" >> /etc/DNSlock/blacklist.list
		fi
	else
		echo "Please Enter a valid domain name"
	fi
done
##Restart DNSMASQ
service dnsmasq restart
