#!/bin/bash

if [ $1 == "--update" ]
then
sudo /etc/DNSlock/update

elif    [ $1 == "--start" ]
	then
	sudo service dnsmasq start

elif    [ $1 == "--stop" ]
        then
        sudo service dnsmasq stop

elif    [ $1 == "--restart" ]
        then
        sudo service dnsmasq restart

elif    [ $1 == "--status" ]
        then
        systemctl is-active dnsmasq.service
elif    [ $1 == "--blacklist" ]
	then
	for i; do
		if [ $i != "--blacklist" ]
		then
		blacklist_domains+=" $i"
		fi
	done
	sudo /etc/DNSlock/blacklist $blacklist_domains
elif    [ $1 == "--whitelist" ]
        then
        for i; do
                if [ $i != "--whitelist" ]
                then
		whitelist_domains+=" $i"
                fi
        done
	sudo /etc/DNSlock/whitelist $whitelist_domains
elif	[ $1 == "--wildcard" ]
	then
	for i; do
		if [ $i != "--wildcard" ]
                then
		wildcard_domains+=" $i"
		fi
	done
	sudo /etc/DNSlock/wildcard $wildcard_domains
elif	[ $1 == "--tail" ]
	then
	sudo tail -f /var/log/DNSlock.log
elif 	[ $1 == "--flush" ]
	then
	sudo truncate /var/log/DNSlock.log --size 0

fi
