#!/bin/bash
##Installation script for DNSlock

##Install DNSMASQ
echo y | apt-get install dnsmasq
##Backup dnsmasq default config file
mv /etc/dnsmasq.conf /etc/dnsmasq.conf.bak
##Download preconfigured dnsmasq config file
wget -O /etc/dnsmasq.conf https://raw.githubusercontent.com/raghavdua1995/DNSlock/master/dnsmasq.conf
mkdir /etc/DNSlock
##Download control script and make it executable
wget -O /etc/DNSlock/DNSlock https://raw.githubusercontent.com/raghavdua1995/DNSlock/master/DNSlock
chmod 0777 /etc/DNSlock/DNSlock
##Download domain blacklisting script and make it executable
wget -O /etc/DNSlock/blacklist https://raw.githubusercontent.com/raghavdua1995/DNSlock/master/blacklist
chmod 0777 /etc/DNSlock/blacklist
##Download domain whitelisting script and make it executable
wget -O /etc/DNSlock/whitelist https://raw.githubusercontent.com/raghavdua1995/DNSlock/master/whitelist
chmod 0777 /etc/DNSlock/whitelist
##Download domain wildcard blacklistng script and make it executable
wget -O /etc/DNSlock/wildcard https://raw.githubusercontent.com/raghavdua1995/DNSlock/master/wildcard
chmod 0777 /etc/DNSlock/wildcard
##Create hosts file: 'contentblock.list', dnsmasq will use contentblock.list as additional hosts file to block content
touch /etc/DNSlock/contentblock.list
chmod 0777 /etc/DNSlock/contentblock.list
##Create hosts file: 'blacklist.list', dnsmasq will use blacklist.list as additional hosts file to blacklist domains
touch /etc/DNSlock/blacklist.list
chmod 0777 /etc/DNSlock/blacklist.list
##Create file: 'whitelist.list', whitelisted domains will written in whitelist.list
touch /etc/DNSlock/whitelist.list
chmod 0777 /etc/DNSlock/whitelist.list
##Delete orignal resolv.conf file and replace it with downloaded resolv.conf file which uses Google's DNS resolvers
rm /etc/resolv.conf
wget -O /etc/resolv.conf https://raw.githubusercontent.com/raghavdua1995/DNSlock/master/resolv.conf
##Download list containing hosts files sources
wget -O /etc/DNSlock/sources.list https://raw.githubusercontent.com/raghavdua1995/DNSlock/master/sources.list
##Download script to pull/update hosts files from sources mentioned in sources.list and make it executable
wget -O /etc/DNSlock/update https://raw.githubusercontent.com/raghavdua1995/DNSlock/master/script
chmod 0777 /etc/DNSlock/update
##Create symbolic link /usr/local/bin/DNSlock ----> /etc/DNSlock/DNSlock
ln -s /etc/DNSlock/DNSlock /usr/local/bin/DNSlock
##Update contentblock.list and restart DNSMASQ
DNSlock --update
service dnsmasq restart
##Install cronjob to:
#Update contentblock.list daily
#Delete log at 23:59 daily
echo "Installing Cronjobs"
wget -O /etc/cron.d/DNSlock-cron https://raw.githubusercontent.com/raghavdua1995/DNSlock/master/DNSlock-cron
chown root /etc/cron.d/DNSlock-cron
chmod 0644 /etc/cron.d/DNSlock-cron
fi
