#!/bin/bash

##Create temporary file where domains from various host file will be written.
touch /etc/DNSlock/common_hosts.list

n=1;

##For loop to download hosts from sources mentioned in sources.list. If download succedes then loop will create new cached list and delete the backup cached list otherwise restore backup cached list

for i in $(cat /etc/DNSlock/sources.list); do
cp /etc/DNSlock/cache _$n.list /etc/DNSlock/cache _$n.list.bak 2>>/dev/null;
echo "Fetching-" $i
curl -s $i > /etc/DNSlock/cache_$n.list; res=$?; n=$((n+1));
if [ "$res" == "0" ]
then
echo "List fetched."
rm /etc/DNSlock/cache _$n.list.bak 2>>/dev/null
else
echo "Failed to fetch list, using catched list instead."
mov /etc/DNSlock/cache _$n.list.bak /etc/DNSlock/cache _$n.list 2>>/dev/null
fi
done

##Copying content from cached lists to common_hosts.list
for((k=1;k<n;k++)); do
cat /etc/DNSlock/cache_$k.list >> /etc/DNSlock/common_hosts.list;
done

rm /etc/DNSlock/contentblock.list

##Processing list
##Remove MS DOS Carriage returns
##Remove 127.0.0.1
##Remove 0.0.0.0
##Remove whitespaces
##Appending '0.0.0.0  ' in front of domain names
##Remove Comments
##Delete any leftover trailing blanks
##Sort and remove duplicate entries
##Store merged entries in contentblock.list( Additional hosts file being used by DNSMASQ to block content )
##Remove first 2 lines ( that is: 0.0.0.0 and 0.0.0.0 0.0.0.0)
echo "Merging Lists"
sudo sed -e 's/\r//' -e 's/127.0.0.1//' -e 's/0.0.0.0//'  -e 's/[[:space:]]*//g' -e 's/^/0.0.0.0	/' -e 's/#.*$//' -e 's/[ \t]*$//' < /etc/DNSlock/common_hosts.list | sort -u > /etc/DNSlock/contentblock.list
sudo sed -i '1,2d' /etc/DNSlock/contentblock.list

echo "Blocking"  $(wc -l < /etc/DNSlock/contentblock.list) "Domains."

##Delete temporary file common_hosts.list
rm /etc/DNSlock/common_hosts.list
