#!/bin/bash

echo "Select a interface for DNSlock to listen on, available interfaces are :"
ls /sys/class/net
read iface < /dev/tty
iface_ip="$(/sbin/ifconfig $iface | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')"
iface_ipv6="$(/sbin/ifconfig eth0 |  awk '/inet6/{print $3}' | cut -d/ -f1)"

##Update blacklist file
sudo sed -i "s|$dnslock_iface_ip|$iface_ip|" /etc/DNSlock/blacklist.list
sudo sed -i "s|$dnslock_iface_ipv6|$iface_ipv6|" /etc/DNSlock/blacklist.list

##Update wildcard and config file
sudo sed -i "s|$dnslock_iface_ip|$iface_ip|" /etc/dnsmasq.conf

##Remove old values
sudo sed -i "/$dnslock_iface/d" /etc/environment
sudo sed -i "/$dnslock_iface_ip/d" /etc/environment
sudo sed -i "/$dnslock_iface_ipv6/d" /etc/environment

##Set new values
sudo echo dnslock_iface=$iface >> /etc/environment
sudo echo dnslock_iface_ip=$iface_ip >> /etc/environment
sudo echo dnslock_iface_ipv6=$iface_ipv6 >> /etc/environment

sudo service dnsmasq restart

echo "Interface/IP address updated, please restart the system for changes to take effect"
