#!/bin/bash
##Removal script for DNSlock

##Remove DNSMASQ and purge configuration files
echo y | apt-get purge dnsmasq
echo y | apt-get purge lighttpd
##Delete DNDlock directory
rm -R /etc/DNSlock/
##Remove symbolic link /usr/local/bin/DNSlock ----> /etc/DNSlock/DNSlock
rm /usr/local/bin/DNSlock
##Delete log file
rm /var/log/DNSlock.log
##Delete cron jobs
rm /etc/cron.d/DNSlock-cron
