#!/bin/sh

##Removing duplicates from sources.list ( Hosts file sources list) and resetting permissions.
sudo awk '!a[$0]++' /etc/DNSlock/sources.list > /tmp/sources.list && cp /tmp/sources.list /etc/DNSlock/
sudo rm /tmp/sources.list
sudo chmod 0777 /etc/DNSlock/sources.list

##Create temporary file where domains from various host file will me written.
touch /etc/DNSlock/common_hosts.list

n=1;

##Ensuring hosts file sources are not blocked ( Unless explicitly blacklisted ) by whitelisting them.
echo "Whitlisting hosts file sources"
for i in $(cat /etc/DNSlock/sources.list); do
domain+=" "
domain+=`echo "$i" | sed -e 's|^[^/]*//||' -e '/^[^@]*@/s///' -e 's|/.*$||'`
done
DNSlock --whitelist $domain

##For loop to download hosts from sources mentioned in sources.list. If download succedes then loop will create new cached list and delete the backup cached list other$

for i in $(cat /etc/DNSlock/sources.list); do
cp /etc/DNSlock/cache _$n.list /etc/DNSlock/cache _$n.list.bak 2>>/dev/null;
echo "Fetching-" $i
curl -s $i > /etc/DNSlock/cache_$n.list; res=$?; n=$((n+1));
if [ "$res" == "0" ]
then
echo "List fetched."
rm /etc/DNSlock/cache _$n.list.bak 2>>/dev/null
else
echo "Failed to fetch list, using cached list instead."
mov /etc/DNSlock/cache _$n.list.bak /etc/DNSlock/cache _$n.list 2>>/dev/null
fi
done

##Copying content from cached lists to common_hosts.list.
for((k=1;k<n;k++)); do
cat /etc/DNSlock/cache_$k.list >> /etc/DNSlock/common_hosts.list;
done

rm /etc/DNSlock/contentblock.list

##Processing list
##Remove MS DOS Carriage returns
##Remove 127.0.0.1
##Remove 0.0.0.0
##Remove whitespaces
##Appending '0.0.0.0  ' in front of domain names
##Remove Comments
##Delete any leftover trailing blanks
##Sort and remove duplicate entries
##Store merged entries in contentblock.list( Additional hosts file being used by DNSMASQ to block content )
##Remove first 2 lines ( that is: 0.0.0.0 and 0.0.0.0 0.0.0.0)
echo "Merging Lists"
sudo sed -e 's/\r//' -e 's/127.0.0.1//' -e 's/0.0.0.0//'  -e 's/[[:space:]]*//g' -e 's/^/0.0.0.0	/' -e 's/#.*$//' -e 's/[ \t]*$//' < /etc/DNSlock/common_hosts.list | sort -u > /etc/DNSlock/contentblock.list
sudo sed -i '1,2d' /etc/DNSlock/contentblock.list

##Remove whitelisted domains
for k in $(cat /etc/DNSlock/whitelist.list); do
sudo sed -i "/0.0.0.0	$k/d" /etc/DNSlock/contentblock.list
done

##Block ipv6 content
sudo cp /etc/DNSlock/contentblock.list /etc/DNSlock/contentblockipv6.list
sudo sed -i 's/0.0.0.0/::1/' /etc/DNSlock/contentblockipv6.list


echo "Blocking"  $(wc -l < /etc/DNSlock/contentblock.list) "Domains."

##Delete temporary file common_hosts.list
rm /etc/DNSlock/common_hosts.list

service dnsmasq restart
