#!/bin/bash

for i; do
        if grep -P '(?=^.{4,253}$)(^(?:[a-zA-Z](?:(?:[a-zA-Z0-9\-]){0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$)' <<< "$i" >> /dev/null ;
        then
                if grep -q -x "$i" "/etc/DNSlock/whitelist.list";
                then
                echo "$i is already in the whitelist, no further action is required."
                else
                        echo "Adding $i to whitelist"
                        echo "$i" >> /etc/DNSlock/whitelist.list
			sudo sed -i "/0.0.0.0	$i/d" /etc/DNSlock/contentblock.list
                fi
        else
                echo "Please Enter a valid domain name"
        fi
done

##Restart DNSMASQ
service dnsmasq restart
