#!/bin/bash
for i; do
 	if grep -q "address=/.$i/$dnslock_iface_ip" "/etc/dnsmasq.conf";
 	then
 	echo "Domain is already wildcard blocked, no further action is required."
 	else
 	echo "address=/.$i/$dnslock_iface_ip" >> /etc/dnsmasq.conf
 	fi
done
##Restart DNSMASQ
service dnsmasq restart
